import zipfile, hashlib, sys
from xml.sax.saxutils import escape

OUT=sys.argv[1] if len(sys.argv)>1 else 'JPN_Gestao_Facil_v0.3_candidata.xlsx'
TS=(2020,1,1,0,0,0)
F={}
F['[Content_Types].xml']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'''+''.join(f'<Override PartName="/xl/worksheets/sheet{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>' for i in range(1,9))+'''<Override PartName="/xl/charts/chart1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/></Types>'''
F['_rels/.rels']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'''
names=['Leia-me','Dashboard','Clientes','Vendas','Tarefas','Estoque','Financeiro','Listas']
F['xl/workbook.xml']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'''+''.join(f'<sheet name="{n}" sheetId="{i}" r:id="rId{i}"/>' for i,n in enumerate(names,1))+'''</sheets><calcPr calcMode="auto"/></workbook>'''
F['xl/_rels/workbook.xml.rels']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'''+''.join(f'<Relationship Id="rId{i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet{i}.xml"/>' for i in range(1,9))+'''<Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
F['xl/styles.xml']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font/><font><b/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B1F33"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf/><xf fontId="1" fillId="2" applyFont="1" applyFill="1"/></cellXfs></styleSheet>'''

def c(ref,val,style=0,formula=None):
    s=f' s="{style}"' if style else ''
    if formula is not None:return f'<c r="{ref}"{s}><f>{escape(formula)}</f><v>{val}</v></c>'
    if isinstance(val,(int,float)):return f'<c r="{ref}"{s}><v>{val}</v></c>'
    return f'<c r="{ref}" t="inlineStr"{s}><is><t>{escape(str(val))}</t></is></c>'
def sh(rows,extra=''):
    body=''.join('<row r="%d">%s</row>'%(ri,''.join(c(*x) for x in cs)) for ri,cs in rows)
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" state="frozen"/></sheetView></sheetViews><sheetData>{body}</sheetData>{extra}</worksheet>'''

F['xl/worksheets/sheet1.xml']=sh([(1,[('A1','JPN Gestão Fácil v0.3 — CANDIDATA',1)]),(2,[('A2','Dados fictícios. Financeiro vazio. Compatibilidade física ainda pendente.')]),(3,[('A3','REPOR é alerta operacional e não autoriza compra.')])])
k=[('Clientes cadastrados',3,'COUNTA(Clientes!B2:B100)'),('Clientes qualificados',1,'COUNTIF(Clientes!E2:E100,"Qualificado")'),('Vendas abertas',2,'COUNTIF(Vendas!E2:E100,"Aberta")'),('Vendas ganhas',1,'COUNTIF(Vendas!E2:E100,"Ganha")'),('Tarefas pendentes',2,'COUNTIF(Tarefas!F2:F100,"Pendente")'),('Itens para reposição',1,'COUNTIF(Estoque!G2:G100,"REPOR")'),('Tarefas vencidas',0,'COUNTIFS(Tarefas!F2:F100,"<>Concluída",Tarefas!F2:F100,"<>",Tarefas!H2:H100,"<>",Tarefas!H2:H100,"<"&TODAY())'),('Saldo registrado',0,'SUMIF(Financeiro!C2:C100,"Entrada",Financeiro!G2:G100)-SUMIF(Financeiro!C2:C100,"Saída",Financeiro!G2:G100)')]
rows=[(1,[('A1','Indicador',1),('B1','Valor',1)])]+[(i+2,[('A'+str(i+2),lab),('B'+str(i+2),v,0,f)]) for i,(lab,v,f) in enumerate(k)]
F['xl/worksheets/sheet2.xml']=sh(rows,'<drawing r:id="rId1"/>')
F['xl/worksheets/_rels/sheet2.xml.rels']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>'''
F['xl/drawings/drawing1.xml']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><xdr:twoCellAnchor><xdr:from><xdr:col>3</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>1</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>9</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>14</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:graphicFrame><xdr:nvGraphicFramePr><xdr:cNvPr id="2" name="Situação das vendas"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:id="rId1"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor></xdr:wsDr>'''
F['xl/drawings/_rels/drawing1.xml.rels']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart1.xml"/></Relationships>'''
F['xl/charts/chart1.xml']='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart><c:title><c:tx><c:rich><a:bodyPr xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"/><a:lstStyle xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"/><a:p xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:r><a:t>Situação das vendas</a:t></a:r></a:p></c:rich></c:tx></c:title><c:plotArea><c:layout/><c:barChart><c:barDir val="col"/><c:grouping val="clustered"/><c:ser><c:idx val="0"/><c:order val="0"/><c:cat><c:strRef><c:f>Dashboard!$A$4:$A$5</c:f></c:strRef></c:cat><c:val><c:numRef><c:f>Dashboard!$B$4:$B$5</c:f></c:numRef></c:val></c:ser><c:axId val="10"/><c:axId val="20"/></c:barChart><c:catAx><c:axId val="10"/><c:crossAx val="20"/></c:catAx><c:valAx><c:axId val="20"/><c:crossAx val="10"/></c:valAx></c:plotArea></c:chart></c:chartSpace>'''
H={3:['ID','Nome/Empresa','Contato','Canal','Etapa','Responsável','Próxima ação','Data da próxima ação','Observações','Atualização'],4:['ID','Data','Cliente','Produto/Serviço','Etapa','Responsável','Quantidade','Valor unitário','Valor total','Próxima ação','Observações'],5:['ID','Tarefa','Categoria','Responsável','Prioridade','Status','Início','Prazo','Próximo passo','Observações'],6:['Código','Item','Categoria','Unidade','Estoque atual','Estoque mínimo','Reposição?','Fornecedor','Observações'],7:['ID','Data','Tipo','Descrição','Categoria','Centro/Projeto','Valor','Status','Vencimento','Observações']}
D={3:[['C001','Cliente Exemplo 1','','WhatsApp','Qualificado'],['C002','Cliente Exemplo 2','','Indicação','Novo'],['C003','Cliente Exemplo 3','','Site','Ativo']],4:[['V001','2026-09-01','Cliente Exemplo 1','Serviço A','Aberta','Equipe',1,0],['V002','2026-09-02','Cliente Exemplo 2','Serviço B','Aberta','Equipe',2,0],['V003','2026-09-03','Cliente Exemplo 3','Serviço C','Ganha','Equipe',1,0]],5:[['T001','Retornar cliente','Comercial','Equipe','Alta','Pendente','2026-09-01','2099-12-31'],['T002','Revisar proposta','Comercial','Equipe','Média','Pendente','2026-09-02','2099-12-31']],6:[['E001','Item Exemplo 1','Geral','un',1,2],['E002','Item Exemplo 2','Geral','un',5,2]],7:[]}
for sn in range(3,8):
    rr=[(1,[(chr(65+i)+'1',h,1) for i,h in enumerate(H[sn])])]
    for rix,row in enumerate(D[sn],2):
        cells=[(chr(65+i)+str(rix),v) for i,v in enumerate(row)]
        if sn==4:cells.append(('I'+str(rix),0,0,f'IF(OR(G{rix}="",H{rix}=""),"",G{rix}*H{rix})'))
        if sn==6:cells.append(('G'+str(rix),'REPOR' if row[4]<=row[5] else 'OK',0,f'IF(OR(B{rix}="",E{rix}="",F{rix}=""),"",IF(E{rix}<=F{rix},"REPOR","OK"))'))
        rr.append((rix,cells))
    extra=f'<autoFilter ref="A1:{chr(64+len(H[sn]))}{max(1,len(rr))}"/>'
    if sn in [3,4,5,7]:extra+='<dataValidations count="1"><dataValidation type="list" sqref="A2:A100"><formula1>Listas!$A$2:$A$10</formula1></dataValidation></dataValidations>'
    F[f'xl/worksheets/sheet{sn}.xml']=sh(rr,extra)
F['xl/worksheets/sheet8.xml']=sh([(1,[('A1','Listas',1)]),(2,[('A2','Novo')]),(3,[('A3','Qualificado')]),(4,[('A4','Aberta')]),(5,[('A5','Ganha')]),(6,[('A6','Pendente')]),(7,[('A7','Concluída')])])
with zipfile.ZipFile(OUT,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as z:
    for name in sorted(F):
        zi=zipfile.ZipInfo(name,TS);zi.compress_type=zipfile.ZIP_DEFLATED;zi.external_attr=0o644<<16;z.writestr(zi,F[name])
b=open(OUT,'rb').read()
print(f'path={OUT}')
print(f'size_bytes={len(b)}')
print(f'sha256={hashlib.sha256(b).hexdigest()}')